--- 
  mysql_root_password_update: yes
  mysql_user_name: devops
  mysql_root_password: ' '
  mysql_databases:
    - name: devopsdemo
      encoding: latin1
      collation: latin1_general_ci
    - name: catalogue
      encoding: latin1
      collation: latin1_general_ci
  mysql_users:
    - name: devops
      host: "%"
      password: devopspass
      priv: "example_db.*:ALL"      
  mysql_bind_address: "0.0.0.0"
  mysql_host: localhost
  mysql_dump_download: /tmp/dump.sql
  